name: Check for updated APP_VERSION and CHANGELOG

on:
  # Triggers the workflow on pull request events for the master branch
  pull_request:
    branches: [ master ]

jobs:
  version_check:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      - name: Get git diff value
        id: main
        run: |
          OUTPUT=$(git diff --exit-code APP_VERSION) &&
          echo "::set-output name=OUTPUT::$OUTPUT"

      - name: Assert file has changed
        if: steps.main.outputs.OUTPUT == 1
        run: |
          echo "APP_VERSION has been updated"

  log_check:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      - name: Check if file has changed
        id: main
        run: |
          OUTPUT=$(git diff --exit-code CHANGELOG.md) &&
          echo "::set-output name=OUTPUT::$OUTPUT"

      - name: Assert file has changed
        if: steps.main.outputs.OUTPUT == 1
        run: |
          echo "CHANGELOG.md has been updated"
