name: Health check extravaganza

# Triggers the workflow on pull request events for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  super-lint:
    name: A job for linting the code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  version_check:
    runs-on: ubuntu-latest
    name: Checks APP_VERSION and CHANGELOG.md files for updates.
    steps:
    - name: Version check action
      uses: mwcodebase/versioning-checker@v0.3-testing
