name: Super-Linter

# Triggers the workflow on pull request events for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  super-lint:
    name: A job for linting the code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  versioning_check:
    name: A job for checking if the APP_VERSION and CHANGELOG files have been updated
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Hello world action step
      id: hello
      uses: actions/versioning-checker
      with:
        who-to-greet: 'Mona the Octocat'
    
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
