name: Check for updated APP_VERSION and CHANGELOG

on:
  # Triggers the workflow on pull request events for the master branch
  pull_request:
    branches: [ master ]

jobs:
  version_check:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Check if file has changed
        run: git diff --exit-code APP_VERSION

  log_check:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Check if file has changed
        run: git diff --exit-code CHANGELOG.md
