name: Check for updated APP_VERSION and CHANGELOG

on:
  # Triggers the workflow on pull request events for the master branch
  pull_request:
    branches: [ master ]

jobs:
  update_checker:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      - name: Gather changed files
        run: git-diff --name-only >> changed.txt

      - name: Check if APP_VERSION has changed
        if: grep -Fq APP_VERSION changed.txt
        run: echo "APP_VERSION has been updated"

      - name: Check if CHANGELOG has changed
        if: grep -Fq CHANGELOG.md changed.txt
        run: echo "CHANGELOG has been updated"
